import { getActiveLocale } from "./i18n";

const backendPhrases: ReadonlyArray<readonly [string, string]> = [
  ["组件检查通过才代表开发所需组件完整；环境生效还需要 current 指针和用户 PATH/JAVA_HOME 命中。", "Passing component checks means the development components are complete; activation also requires the current pointer and the user PATH/JAVA_HOME to match."],
  ["目录存在只代表文件夹存在；版本命令通过才代表基本能运行。", "A directory only proves the folder exists; a successful version command proves the runtime can start."],
  ["命中 WindowsApps Store Alias 时，DevEnv Manager 不会自动关闭别名或删除 WindowsApps PATH。", "When a WindowsApps Store Alias is detected, DevEnv Manager will not disable the alias or remove WindowsApps from PATH automatically."],
  ["当前 DevEnv Manager 进程 PATH 与用户 PATH 不一致；请重启终端或 IDE 后验证。", "The current DevEnv Manager process PATH differs from the user PATH; restart the terminal or IDE and verify again."],
  ["当前进程 PATH 与最新用户 PATH 不一致；修复后需要重新打开终端和 IDE", "The current process PATH differs from the latest user PATH; reopen terminals and IDEs after repair."],
  ["pip 与当前 python -m pip 不一致，或当前 Python 缺少 pip。建议使用 python -m pip。", "pip does not match the current python -m pip, or the current Python has no pip. Use python -m pip."],
  ["当前 python -m pip 不可用；只有受管 Python 才允许生成 pip 修复计划。", "The current python -m pip is unavailable; a pip repair plan can only be created for managed Python."],
  ["只检查明确命名的缓存、临时和日志目录，不进入文档、备份或云同步数据", "Only explicitly named cache, temporary, and log directories are inspected; documents, backups, and cloud-synced data are excluded."],
  ["Phase 2 仅允许清理明确选择且通过二次校验的低/中风险项目", "Phase 2 only cleans explicitly selected low/medium-risk items that pass a second validation."],
  ["安全边界：默认扫描不会进入桌面、下载、文档、图片、视频或音乐目录", "Safety boundary: the default scan does not enter Desktop, Downloads, Documents, Pictures, Videos, or Music."],
  ["Maven、Gradle、Cargo、Windows Temp、回收站、WPS 与系统缓存保持只读", "Maven, Gradle, Cargo, Windows Temp, Recycle Bin, WPS, and system caches remain read-only."],
  ["JAVA_HOME 是间接引用；部分程序不会二次展开，建议写入真实绝对路径。", "JAVA_HOME is an indirect reference; some programs do not expand it twice. Use a real absolute path."],
  ["JAVA_HOME\\bin\\javac.exe 不存在；可能是 JRE 或残缺 JDK。", "JAVA_HOME\\bin\\javac.exe does not exist; this may be a JRE or an incomplete JDK."],
  ["当前 PATH 没有可执行 python，不能对未知 Python 执行 ensurepip。", "No executable python is available on PATH, so ensurepip cannot run against an unknown Python installation."],
  ["尚未安装受管 Python；无法直接切换到 DevEnv 管理版本。", "No managed Python is installed, so DevEnv Manager cannot switch to a managed version."],
  ["Microsoft Store Python Alias 可能抢占 python 命令。", "The Microsoft Store Python Alias may take precedence over the python command."],
  ["Microsoft Store Python 执行别名可能抢占 python 命令", "The Microsoft Store Python execution alias may take precedence over the python command."],
  ["本程序不会自动关闭 Microsoft Store Alias，只会提示你打开系统设置手动处理。", "DevEnv Manager does not disable Microsoft Store aliases automatically; it only opens the system setting for manual changes."],
  ["安装包时尽量使用 python -m pip，而不是直接运行 pip。", "Use python -m pip instead of invoking pip directly when installing packages."],
  ["优先使用 python -m pip，避免 pip.exe 与 Python 版本不一致。", "Prefer python -m pip to avoid a pip.exe and Python version mismatch."],
  ["优先使用 DevEnv Manager 受管 Python 或官网安装版 Python。", "Prefer a DevEnv Manager managed Python or an official Python installation."],
  ["打开 Windows 应用执行别名设置，人工关闭 python.exe / python3.exe Store Alias。", "Open Windows App Execution Aliases and manually disable the python.exe / python3.exe Store aliases."],
  ["重新检测 Python 环境，确认新终端和 IDE 已继承最新 PATH。", "Inspect Python again and confirm that new terminals and IDEs inherit the latest PATH."],
  ["导出只读 Python 诊断报告，发给自己或 issue 复盘。", "Export the read-only Python diagnostic report for local review or an issue."],
  ["安装受管 Python，再用预览计划切换；不会删除系统 Python。", "Install managed Python and switch with a previewed plan; system Python will not be removed."],
  ["切换到已安装的受管 Python，并生成用户级 PATH 修复计划。", "Switch to an installed managed Python and create a user PATH repair plan."],
  ["受管路径置前并去重；不删除外部工具路径", "Prepend and deduplicate managed paths without removing external tool paths."],
  ["只修改当前用户环境变量；已打开的终端和 IDE 不会自动刷新", "Only current-user environment variables are changed; open terminals and IDEs are not refreshed automatically."],
  ["仅在已验证 JDK 可用时设置", "Set only when a verified JDK is available."],
  ["DevEnv Manager 受管目录根路径", "DevEnv Manager managed root directory."],
  ["JAVA_HOME\\bin\\java.exe 不存在。", "JAVA_HOME\\bin\\java.exe does not exist."],
  ["PATH 首个 java.exe 不属于 JAVA_HOME。", "The first java.exe on PATH is not under JAVA_HOME."],
  ["PATH 首个 javac.exe 不属于 JAVA_HOME。", "The first javac.exe on PATH is not under JAVA_HOME."],
  ["JAVA_HOME 指向了 bin 目录；应指向 JDK 根目录。", "JAVA_HOME points to the bin directory; it must point to the JDK root."],
  ["pip 与当前 python -m pip 不一致或当前 Python 缺少 pip", "pip does not match the current python -m pip, or the current Python has no pip."],
  ["未发现明显 Python 冲突", "No obvious Python conflict was detected."],
  ["组件缺失不会显示为完全可用。", "A runtime with missing components is not reported as fully usable."],
  ["安装失败不会写入 installed.json；本报告只检查已登记记录。", "Failed installations are not written to installed.json; this report only checks registered records."],
  ["current 指针和环境生效是独立状态，请重新打开终端/IDE 后验证。", "The current pointer and environment activation are separate states; reopen the terminal/IDE and verify again."],
  ["Windows 系统目录仅统计，不允许清理", "Windows system directory: measured only; cleanup is not allowed."],
  ["24 小时内的临时项目受保护", "Temporary items modified within 24 hours are protected."],
  ["24 小时内的日志受保护", "Logs modified within 24 hours are protected."],
  ["系统、项目或用户关键目录受保护", "System, project, or critical user directories are protected."],
  ["DevEnv Manager 受管运行时受保护", "DevEnv Manager managed runtimes are protected."],
  ["浏览器身份凭据受保护", "Browser credentials are protected."],
  ["微信/QQ 用户数据库受保护", "WeChat/QQ user databases are protected."],
  ["浏览器用户目录受保护", "Browser user directories are protected."],
  ["用户 Temp 可评估；Windows Temp 永远只统计", "User Temp can be evaluated; Windows Temp is always measured only."],
  ["错误报告、缩略图和 DirectX Shader Cache 仅统计", "Error reports, thumbnails, and the DirectX Shader Cache are measured only."],
  ["仅估算回收站占用，不读取或清空内容", "Only Recycle Bin usage is estimated; contents are not read or emptied."],
  ["下载和日志可评估，config 只统计", "Downloads and logs can be evaluated; config is measured only."],
  ["包管理器和构建工具可再生成缓存", "Package-manager and build-tool caches can be regenerated."],
  ["系统诊断数据仅统计", "System diagnostic data is measured only."],
  ["包含缩略图缓存，始终只统计", "Contains thumbnail cache and is always measured only."],
  ["缩略图缓存仅统计", "Thumbnail cache is measured only."],
  ["DirectX 缓存仅统计", "DirectX cache is measured only."],
  ["回收站默认不清理", "Recycle Bin cleanup is disabled by default."],
  ["配置目录只统计，不清理", "The configuration directory is measured only and is not cleaned."],
  ["开发缓存请使用对应工具的官方清理命令", "Use the corresponding tool's official command to clean development caches."],
  ["WPS 类别在本版本仅预览，防止误伤备份或云文档", "The WPS category is preview-only in this version to protect backups and cloud documents."],
  ["桌面归档不会移动快捷方式、隐藏文件和系统文件", "Desktop archive does not move shortcuts, hidden files, or system files."],
  ["用户资料目录需要二次确认；建议先备份重要文件", "User profile folders require an additional confirmation; back up important files first."],
  ["目录较大，估算可能被截断；执行前会重新校验", "The directory is large and the estimate may be truncated; it will be revalidated before execution."],
  ["Junction 会把原路径桥接到目标盘；执行前请关闭相关程序。", "The Junction bridges the original path to the target drive; close related applications before execution."],
  ["执行时会再次校验桌面边界、文件大小和源文件 SHA-256", "Execution revalidates the Desktop boundary, file size, and source-file SHA-256."],
  ["目标冲突使用计划中预览的唯一文件名，不覆盖现有文件", "Target conflicts use the unique file name previewed in the plan; existing files are never overwritten."],
  ["跨盘复制完成并验证目标 SHA-256 后才会删除源文件", "The source file is removed only after the cross-drive copy completes and the target SHA-256 is verified."],
  ["文件只会移动到 Windows 回收站，不会永久删除", "Files are moved only to Windows Recycle Bin and are not permanently deleted."],
  ["执行时会再次校验桌面边界、文件大小和 SHA-256", "Execution revalidates the Desktop boundary, file size, and SHA-256."],
  ["恢复时请打开回收站并使用 Windows 的还原操作", "To recover a file, open Windows Recycle Bin and use Restore."],
  ["本阶段只生成整理建议，不删除或移动桌面/下载文件", "This stage only creates organization suggestions; it does not delete or move Desktop or Downloads files."],
  ["旧安装包在归档前应确认对应软件已安装且安装包可重新获取", "Before archiving an old installer, confirm that the software is installed and the installer can be obtained again."],
  ["目录条目超过扫描上限，结果为上限内估算", "The directory exceeded the scan limit; the result is an estimate within that limit."],
  ["只展示占用；请通过应用内置设置备份、迁移或清理", "Usage is shown for inspection only; use the application's settings to back up, move, or clean its data."],
  ["仅统计路径和文件大小元数据，不读取账号、聊天正文或文件内容", "Only path and file-size metadata are measured; account data, chat contents, and file contents are not read."],
  ["本页面不会删除应用数据、登录数据或安装目录", "This page does not delete application data, sign-in data, or installation directories."],
  ["临时文件占用", "Temporary-file usage"],
  ["Windows 错误报告", "Windows error reports"],
  ["系统错误报告", "System error reports"],
  ["DirectX 着色器缓存", "DirectX shader cache"],
  ["Windows 回收站占用", "Windows Recycle Bin usage"],
  ["已下载的安装缓存", "Downloaded installation cache"],
  ["超过 24 小时的旧日志", "Logs older than 24 hours"],
  ["应用配置与状态数据", "Application configuration and state data"],
  ["应用配置", "Application configuration"],
  ["开发工具可再生成缓存", "Regenerable development-tool cache"],
  ["WPS 明确缓存/临时/日志路径", "Explicit WPS cache/temporary/log path"],
  ["C 盘临时文件", "C: temporary files"],
  ["Windows 系统缓存", "Windows system caches"],
  ["Windows 回收站", "Windows Recycle Bin"],
  ["DevEnv Manager 自身", "DevEnv Manager data"],
  ["开发缓存", "Development caches"],
  ["WPS 临时文件与日志", "WPS temporary files and logs"],
  ["Java 生效链不一致", "Java activation chain mismatch"],
  ["Python / pip 可能不一致", "Possible Python / pip mismatch"],
  ["JDK 生效链", "JDK activation chain"],
  ["JAVA_HOME 不包含可用的 java.exe 与 javac.exe", "JAVA_HOME does not contain usable java.exe and javac.exe."],
  ["JAVA_HOME 与用户 PATH 首个 java.exe 不一致", "JAVA_HOME does not match the first java.exe on the user PATH."],
  ["未发现 JAVA_HOME；安装或切换 JDK 后会自动配置", "JAVA_HOME was not found; it is configured after installing or switching a JDK."],
  ["未设置，点击“配置”写入受管根目录", "Not configured; use Configure to write the managed root."],
  ["已登记但目录不存在", "Registered but directory is missing"],
  ["已登记但不可用", "Registered but unusable"],
  ["已安装但环境未生效", "Installed but not active in the environment"],
  ["组件缺失", "Missing components"],
  ["当前生效", "Active"],
  ["目录存在", "Directory exists"],
  ["可执行文件存在", "Executable exists"],
  ["验证通过", "Verification passed"],
  ["需配置", "Needs configuration"],
  ["需清理", "Needs cleanup"],
  ["未安装", "Not installed"],
  ["未设置", "Not configured"],
  ["异常", "Problem detected"],
  ["正常", "Healthy"],
  ["可用", "Usable"],
  ["不可用", "Unavailable"],
  ["未发现", "Not detected"],
];

const backendPatterns: ReadonlyArray<readonly [RegExp, string]> = [
  [/发现 (\d+) 个 Python，命令命中取决于 PATH 顺序。/g, "Found $1 Python installations; command resolution depends on PATH order."],
  [/发现 (\d+) 个 pip，pip\.exe 可能不属于当前 python\.exe。/g, "Found $1 pip executables; pip.exe may not belong to the current python.exe."],
  [/PATH\/注册表中发现 (\d+) 个 Python，pip 容易安装到错误版本/g, "Found $1 Python installations on PATH/in the registry; pip may install into the wrong version."],
  [/(\d+) 个条目，没有真实失效或重复项/g, "$1 entries; no genuinely missing or duplicate entries."],
  [/(\d+) 个条目/g, "$1 entries"],
  [/重复 PATH:/g, "Duplicate PATH:"],
  [/失效 PATH:/g, "Missing PATH:"],
  [/已排除不可自动清理项：/g, "Excluded an item that cannot be cleaned automatically: "],
  [/(\d+) 个选择项已失效或不属于本轮扫描/g, "$1 selected items are stale or do not belong to this scan"],
  [/<应用时间>/g, "<apply-time>"],
];

export function localizeBackendText(value: unknown): string {
  const text = String(value ?? "");
  if (getActiveLocale() !== "en-US" || !/[\u3400-\u9fff]/.test(text)) return text;

  let translated = text;
  for (const [chinese, english] of backendPhrases) {
    translated = translated.split(chinese).join(english);
  }
  for (const [pattern, replacement] of backendPatterns) {
    translated = translated.replace(pattern, replacement);
  }
  return translated;
}
