from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / "artifacts"
REPORT = ARTIFACTS / "feature-acceptance-report.json"
CHECKLIST = ARTIFACTS / "manual-smoke-checklist.md"


DEFAULT_ITEMS = [
    "Runtime 页面最大化窗口下安装分组是否清楚，是否仍挤成一行。",
    "Ports 页面是否能看到每行可关闭/不可关闭原因。",
    "Cleanup 页面是否能看到磁盘概览、重复大文件、桌面归档、下载归档入口。",
    "File Associations 是否能快速搜索 `.txt`、`.md`、`.json`。",
    "Dark 和 High Contrast 模式下说明卡、表格和按钮是否可读。",
    "操作失败或成功后是否还有空白 toast 或只有 toast 没有页面结果。",
]


def main() -> int:
    ARTIFACTS.mkdir(exist_ok=True)
    report = {}
    if REPORT.exists():
        report = json.loads(REPORT.read_text(encoding="utf-8"))

    manual_cases = [case for case in report.get("cases", []) if case.get("status") == "manual"]
    lines = [
        "# DevEnv Manager Manual Smoke Checklist",
        "",
        "This list is generated by `scripts/generate_manual_smoke_checklist.py`.",
        "",
        "## Required Visual Checks",
        "",
    ]
    for index, item in enumerate(DEFAULT_ITEMS, 1):
        lines.append(f"{index}. [ ] {item}")
    if manual_cases:
        lines.extend(["", "## Manual Cases From Acceptance Report", ""])
        for case in manual_cases:
            lines.append(f"- [ ] `{case.get('caseId')}`: {case.get('reason')}")
    CHECKLIST.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Manual smoke checklist written: {CHECKLIST.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
