import type { CleanupWorkbenchState } from "../features/cleanup/state";
import type { FileAssociationUiState } from "../features/fileAssociations/state";
import type { PortsWorkbenchState } from "../features/ports/state";
import { portRecordKey } from "../features/ports/portSafety";
import type { RuntimeWorkbenchState } from "../features/runtimes/state";
import type { PortRecord } from "../types";

const portsRecords = [
  {
    protocol: "TCP",
    localAddress: "0.0.0.0",
    localPort: 445,
    remoteAddress: "",
    remotePort: 0,
    state: "Listen",
    pid: 4,
    processName: "System",
    processPath: "",
    serviceNames: [],
    identity: "system",
    risk: "critical",
    riskLevel: "critical",
    confidence: 1,
    recommendation: "Protected system endpoint.",
    explanation: "Protected system endpoint.",
  },
  {
    protocol: "TCP",
    localAddress: "127.0.0.1",
    localPort: 43595,
    remoteAddress: "",
    remotePort: 0,
    state: "Listen",
    pid: 9152,
    processName: "tomcat10",
    processPath: "C:\\Program Files\\Tomcat\\bin\\tomcat10.exe",
    serviceNames: ["ANSYSLicensingTomcat"],
    identity: "service-owned",
    risk: "high",
    riskLevel: "high",
    confidence: 0.95,
    recommendation: "Use service flow.",
    explanation: "Service-owned endpoint.",
  },
  {
    protocol: "TCP",
    localAddress: "127.0.0.1",
    localPort: 18765,
    remoteAddress: "",
    remotePort: 0,
    state: "Listen",
    pid: 1644,
    processName: "python",
    processPath: "C:\\Users\\David\\AppData\\Local\\Programs\\Python\\Python313\\python.exe",
    serviceNames: [],
    identity: "user-dev",
    risk: "medium",
    riskLevel: "medium",
    confidence: 0.98,
    recommendation: "Disposable user/dev candidate.",
    explanation: "Temporary local listener.",
  },
] as unknown as PortRecord[];

export const portsAcceptanceFixture: PortsWorkbenchState = {
  records: portsRecords,
  history: [],
  services: [],
  plan: {
    planId: "port-plan-18765",
    createdAt: "2026-07-09T00:00:00Z",
    expiresAt: "2026-07-09T00:30:00Z",
    riskLevel: "high",
    pid: 1644,
    port: 18765,
    protocol: "TCP",
    processName: "python",
    processPath: "C:\\Users\\David\\AppData\\Local\\Programs\\Python\\Python313\\python.exe",
    parentPid: undefined,
    parentProcessName: undefined,
    serviceNames: [],
    relatedPorts: [18765],
    recommendedActions: ["Terminate disposable python listener"],
    warnings: ["Acceptance fixture only"],
    fingerprint: "fixture-port-plan",
  } as unknown as PortsWorkbenchState["plan"],
  executionResult: {
    planId: "port-plan-18765",
    success: true,
    message: "Port released.",
    targetPort: 18765,
    targetPid: 1644,
    processName: "python",
    serviceOwned: false,
    requiresAdmin: false,
    pidExited: true,
    portReleased: true,
    releaseCheckedAt: "2026-07-09T00:00:10Z",
    failureReason: "",
    nextSteps: [],
    remainingOwners: [],
  } as unknown as PortsWorkbenchState["executionResult"],
  selectedPort: 18765,
  selectedKey: portRecordKey(portsRecords[2]),
  filter: "",
  scanError: "",
  historyError: "",
  servicesError: "",
  planError: "",
  diagnosticsResult: "Diagnostics copied for 18765/PID 1644.",
  retryPlanRequest: null,
  page: 1,
};

export const cleanupAcceptanceFixture: CleanupWorkbenchState = {
  scan: null,
  architecture: null,
  overview: {
    cDrive: {
      drive: "C:",
      totalBytes: 512000000000,
      freeBytes: 128000000000,
      usedBytes: 384000000000,
      usedPercent: 75,
      fileSystem: "NTFS",
      risk: "low",
    },
    volumes: [],
    safeCleanEstimate: 1024,
    moveEstimate: 4096,
    devCacheEstimate: 2048,
    largeFileCount: 2,
    startupCount: 1,
    riskLevel: "low",
    summary: "Fixture overview",
    suggestions: ["Fixture overview"],
  } as unknown as CleanupWorkbenchState["overview"],
  diskOverview: [
    {
      drive: "C:",
      totalBytes: 512000000000,
      freeBytes: 128000000000,
      usedBytes: 384000000000,
      usedPercent: 75,
      fileSystem: "NTFS",
      risk: "low",
    },
  ],
  partition: null,
  plan: null,
  cleanupResult: null,
  movePlan: null,
  moveOperationResult: "Fixture move source selected.",
  moveSource: "",
  moveTargetDrive: "D",
  moveMode: "archive",
  expansionPlan: null,
  expansionResult: null,
  desktop: null,
  downloads: null,
  largeFiles: [],
  largeFilesPage: 1,
  duplicateGroups: [],
  duplicateGroupsPage: 1,
  duplicateScanStatus: "completedEmpty",
  duplicateScanRoot: "C:\\Temp\\devenv-duplicate-empty",
  duplicateScanMinSizeMb: 1,
  duplicateScanElapsedMs: 42,
  duplicateScanCompletedAt: "2026-07-10 12:00:00",
  desktopArchivePlan: null,
  desktopArchiveResult: null,
  downloadsArchivePlan: null,
  downloadsArchiveResult: null,
  rollbackRecords: [],
  selectedIds: [],
  errors: { createPlan: "Select at least one cleanable item." },
};

export const runtimeAcceptanceFixture: RuntimeWorkbenchState = {
  runtimes: [
    {
      kind: "jdk",
      version: "21.0.4",
      executable: "C:\\DevEnv\\runtimes\\jdk-21\\bin\\java.exe",
      source: "managed",
    },
    {
      kind: "python",
      version: "3.13.0",
      executable: "C:\\Users\\David\\AppData\\Local\\Programs\\Python\\Python313\\python.exe",
      source: "external",
    },
  ],
  distributions: [{ id: "temurin", name: "Temurin", recommended: true }] as unknown as RuntimeWorkbenchState["distributions"],
  strongVerification: null,
  selectedRuntimeId: null,
  operationResult: "Runtime fixture operation result.",
  operationError: "",
  page: 1,
};

export const fileAssociationsAcceptanceFixture: FileAssociationUiState = {
  report: {
    totalExtensions: 3,
    manageableExtensions: 3,
    missingAppCount: 0,
    records: [
      { extension: ".txt", currentAppName: "Notepad", risk: "low", source: "registry" },
      { extension: ".md", currentAppName: "VS Code", risk: "low", source: "registry" },
      { extension: ".json", currentAppName: "VS Code", risk: "low", source: "registry" },
    ],
  } as unknown as FileAssociationUiState["report"],
  backups: [{ backupName: "assoc-backup-fixture", createdAt: "2026-07-09T00:00:00Z", path: "C:\\Temp\\assoc-backup.json" }] as unknown as FileAssociationUiState["backups"],
  plan: {
    planId: "assoc-plan-fixture",
    targetAppName: "VS Code",
    targetExecutable: "C:\\Program Files\\Microsoft VS Code\\Code.exe",
    backupPath: "C:\\Temp\\assoc-backup.json",
    warnings: [],
    changes: [],
  } as unknown as FileAssociationUiState["plan"],
  activeTab: "overview",
  filter: { keyword: ".txt", risk: "", category: "", onlyMissingApp: false },
  selectedExtensions: new Set([".txt"]),
  targetAppName: "VS Code",
  targetExecutable: "C:\\Program Files\\Microsoft VS Code\\Code.exe",
  appSearch: null,
  appSearchStatus: "idle",
  appSearchError: "",
  applyResult: null,
  rollbackResult: null,
  selectionResult: "Executable selected.",
  applyResultMessage: "Fixture apply result.",
  operationError: "",
};

export const acceptanceFixtures = {
  ports: portsAcceptanceFixture,
  cleanup: cleanupAcceptanceFixture,
  runtimes: runtimeAcceptanceFixture,
  fileAssociations: fileAssociationsAcceptanceFixture,
};
