import type { CleanupWorkbenchState } from "../features/cleanup/state";
import type { FileAssociationUiState } from "../features/fileAssociations/state";
import type { PortsWorkbenchState } from "../features/ports/state";
import { portRecordKey } from "../features/ports/portSafety";
import type { RuntimeWorkbenchState } from "../features/runtimes/state";
import { toolchainWorkbenchInitialState, type ToolchainWorkbenchState } from "../features/toolchains/state";
import type { PortRecord } from "../types";

const acceptanceTool = (name: string, path: string) => ({ name, installed: true, version: "fixture-1.0", path, detail: "acceptance fixture" });

const portRecord = (overrides: Partial<PortRecord>): PortRecord => ({
  groupId: "port-group-fixture",
  groupFingerprint: "group-fingerprint-fixture",
  protocol: "TCP",
  localAddress: "127.0.0.1",
  localPort: 18765,
  remoteAddress: "*",
  state: "LISTENING",
  pid: 1644,
  processStartTime: 1784213400,
  processName: "python.exe",
  friendlyNameZh: "Python 进程，具体应用未知",
  friendlyNameEn: "Python process, application unknown",
  processPath: "C:\\Tools\\Python\\python.exe",
  productName: "Python",
  fileDescription: "Python",
  companyName: "Python Software Foundation",
  publisher: "Python Software Foundation",
  commandLine: "python -m http.server 18765",
  commandLineFingerprint: "command-fixture",
  parentPid: 1000,
  parentProcessName: "powershell.exe",
  serviceNames: [],
  serviceDisplayNames: [],
  serviceStates: [],
  serviceStartModes: [],
  bindings: [{ localAddress: "127.0.0.1", localEndpoint: "127.0.0.1:18765", remoteEndpoint: "*", state: "LISTENING" }],
  bindingCount: 1,
  remoteConnectionCount: 0,
  relatedPorts: [18765],
  sourceRecordCount: 1,
  hasIpv4: true,
  hasIpv6: false,
  scanSources: [{ source: "fixture", scannedAt: 1784213500, recordCount: 1, fallback: false, conflicts: [] }],
  commonUsage: "Python",
  explanation: "Acceptance identity evidence.",
  risk: "developer-candidate",
  identity: "Python 进程，具体应用未知",
  identityId: "python-runtime",
  identityCategory: "python",
  identityEcosystem: "python",
  confidence: 80,
  confidenceLevel: "high",
  identityCatalogVersion: "1.0.0",
  evidenceCount: 2,
  conflictCount: 0,
  riskLevel: "low",
  recommendation: "确认进程后创建计划。",
  recommendationZh: "确认进程后创建计划。",
  recommendationEn: "Create a plan after confirming the process.",
  evidence: ["executable name matched", "installation path matched"],
  conflictEvidence: [],
  ...overrides,
});

const portsRecords: PortRecord[] = [
  portRecord({
    groupId: "port-group-system-445",
    groupFingerprint: "system-445",
    localAddress: "0.0.0.0",
    localPort: 445,
    pid: 4,
    processName: "System",
    friendlyNameZh: "Windows 系统进程",
    friendlyNameEn: "Windows system process",
    processPath: "",
    bindings: [
      { localAddress: "0.0.0.0", localEndpoint: "0.0.0.0:445", remoteEndpoint: "*", state: "LISTENING" },
      { localAddress: "::", localEndpoint: "[::]:445", remoteEndpoint: "*", state: "LISTENING" },
    ],
    bindingCount: 2,
    hasIpv6: true,
    identity: "Windows 系统进程",
    identityId: "windows-system",
    identityCategory: "system",
    risk: "protected-system",
    riskLevel: "critical",
    confidence: 100,
    confidenceLevel: "verified",
    recommendation: "受保护的系统端口。",
    recommendationZh: "受保护的系统端口。",
    recommendationEn: "Protected system endpoint.",
    explanation: "Protected system endpoint.",
  }),
  portRecord({
    groupId: "port-group-service-43595",
    groupFingerprint: "service-43595",
    localAddress: "127.0.0.1",
    localPort: 43595,
    pid: 9152,
    processName: "tomcat10.exe",
    friendlyNameZh: "Apache Tomcat",
    friendlyNameEn: "Apache Tomcat",
    processPath: "C:\\Program Files\\Tomcat\\bin\\tomcat10.exe",
    serviceNames: ["ANSYSLicensingTomcat"],
    serviceDisplayNames: ["ANSYS Licensing Tomcat"],
    serviceStates: ["Running"],
    serviceStartModes: ["Auto"],
    bindings: [{ localAddress: "127.0.0.1", localEndpoint: "127.0.0.1:43595", remoteEndpoint: "*", state: "LISTENING" }],
    relatedPorts: [43595],
    identity: "Apache Tomcat",
    identityId: "tomcat",
    identityCategory: "java",
    risk: "service-owned",
    riskLevel: "high",
    confidence: 95,
    confidenceLevel: "verified",
    recommendation: "使用服务管理流程。",
    recommendationZh: "使用服务管理流程。",
    recommendationEn: "Use service management.",
    explanation: "Service-owned endpoint.",
  }),
  portRecord({}),
];
export const portsAcceptanceFixture: PortsWorkbenchState = {
  records: portsRecords,
  snapshot: {
    scanId: "acceptance-port-scan",
    scope: "recommended",
    status: "success",
    source: "fixture",
    scannedAt: 1784213500,
    elapsedMs: 42,
    rawCount: 2,
    filteredCount: 2,
    truncated: false,
    cached: true,
    complete: true,
    userMessage: "",
    debugSummary: "fixture snapshot",
    records: portsRecords,
  },
  scanScope: "recommended",
  history: [],
  services: [],
  plan: {
    planId: "port-plan-18765",
    groupId: "port-group-fixture",
    groupFingerprint: "group-fingerprint-fixture",
    scanId: "acceptance-port-scan",
    createdAt: 1784213500,
    expiresAt: 1784213620,
    riskLevel: "high",
    pid: 1644,
    port: 18765,
    protocol: "TCP",
    processStartTime: 1784213400,
    processName: "python.exe",
    processPath: "C:\\Tools\\Python\\python.exe",
    commandLineFingerprint: "command-fixture",
    parentPid: undefined,
    parentProcessName: undefined,
    childProcesses: [],
    serviceNames: [],
    bindings: [{ localAddress: "127.0.0.1", localEndpoint: "127.0.0.1:18765", remoteEndpoint: "*", state: "LISTENING" }],
    relatedPorts: [18765],
    expectedOwnerIdentity: "owner-fixture",
    recommendedActions: ["Terminate disposable python listener"],
    warnings: ["Acceptance fixture only"],
  },
  executionResult: {
    planId: "port-plan-18765",
    success: true,
    message: "Port released.",
    targetPort: 18765,
    targetPid: 1644,
    processName: "python.exe",
    serviceOwned: false,
    requiresAdmin: false,
    pidExited: true,
    portReleased: true,
    relatedPortsReleased: true,
    remainingRelatedPorts: [],
    releaseCheckedAt: "2026-07-09T00:00:10Z",
    failureReason: "",
    nextSteps: [],
    remainingOwners: [],
  } as unknown as PortsWorkbenchState["executionResult"],
  selectedPort: 18765,
  selectedKey: portRecordKey(portsRecords[2]),
  filter: "",
  scanError: "",
  historyError: "",
  servicesError: "",
  planError: "",
  diagnosticsResult: "Diagnostics copied for 18765/PID 1644.",
  retryPlanRequest: null,
  page: 1,
};

export const cleanupAcceptanceFixture: CleanupWorkbenchState = {
  scan: null,
  architecture: null,
  overview: {
    cDrive: {
      drive: "C:",
      totalBytes: 512000000000,
      freeBytes: 128000000000,
      usedBytes: 384000000000,
      usedPercent: 75,
      fileSystem: "NTFS",
      risk: "low",
    },
    volumes: [],
    safeCleanEstimate: 1024,
    moveEstimate: 4096,
    devCacheEstimate: 2048,
    largeFileCount: 2,
    startupCount: 1,
    riskLevel: "low",
    summary: "Fixture overview",
    suggestions: ["Fixture overview"],
  } as unknown as CleanupWorkbenchState["overview"],
  diskOverview: [
    {
      drive: "C:",
      totalBytes: 512000000000,
      freeBytes: 128000000000,
      usedBytes: 384000000000,
      usedPercent: 75,
      fileSystem: "NTFS",
      risk: "low",
    },
  ],
  partition: null,
  plan: null,
  cleanupResult: null,
  movePlan: null,
  moveOperationResult: "Fixture move source selected.",
  moveSource: "",
  moveTargetDrive: "D",
  moveMode: "archive",
  expansionPlan: null,
  expansionResult: null,
  expansionBackupReceipt: "",
  desktop: {
    name: "Desktop rescue",
    path: "C:\\Users\\Fixture\\Desktop",
    totalBytes: 2048,
    fileCount: 1,
    folderCount: 0,
    protectedCount: 0,
    categories: [
      {
        name: "Documents",
        path: "C:\\Users\\Fixture\\Desktop",
        size: 2048,
        category: "Documents",
        suggestion: "Fixture candidate",
        details: [
          {
            fileName: "old-notes.txt",
            path: "C:\\Users\\Fixture\\Desktop\\old-notes.txt",
            directory: "C:\\Users\\Fixture\\Desktop",
            extension: "txt",
            size: 2048,
            modifiedAt: "1700000000",
            fileType: "文档",
            sourceCategory: "Desktop / Documents",
            exists: true,
            canOpen: true,
            canLocate: true,
            openStatus: "Fixture file exists",
            suggestion: "Archive after review",
            risk: "low",
            actionable: true,
            blockedReason: null,
          },
        ],
      },
    ],
    topFiles: [],
    suggestions: ["Review before selecting"],
    warnings: [],
  },
  downloads: null,
  largeFiles: [],
  largeFilesPage: 1,
  duplicateGroups: [],
  duplicateGroupsPage: 1,
  duplicateScanStatus: "completedEmpty",
  duplicateScanRoot: "C:\\Temp\\devenv-duplicate-empty",
  duplicateScanMinSizeMb: 1,
  duplicateScanElapsedMs: 42,
  duplicateScanCompletedAt: "2026-07-10 12:00:00",
  desktopArchivePlan: null,
  desktopArchiveResult: null,
  desktopCleanupPlan: null,
  desktopCleanupResult: null,
  desktopSelectedPaths: [],
  desktopTargetDrive: "D",
  desktopRecoveryResult: "",
  downloadsArchivePlan: null,
  downloadsArchiveResult: null,
  appUsage: null,
  archiveItems: [],
  archivePlan: null,
  archiveResult: null,
  archiveSource: "",
  archiveSourceLabel: "acceptance fixture",
  archiveTargetDrive: "D",
  rollbackRecords: [],
  selectedIds: [],
  errors: { createPlan: "Select at least one cleanable item." },
};

export const runtimeAcceptanceFixture: RuntimeWorkbenchState = {
  runtimes: [
    {
      kind: "jdk",
      version: "21.0.4",
      executable: "C:\\DevEnv\\runtimes\\jdk-21\\bin\\java.exe",
      source: "managed",
    },
    {
      kind: "python",
      version: "3.13.0",
      executable: "C:\\Users\\David\\AppData\\Local\\Programs\\Python\\Python313\\python.exe",
      source: "external",
    },
  ],
  distributions: [{ id: "temurin", name: "Temurin", recommended: true }] as unknown as RuntimeWorkbenchState["distributions"],
  strongVerification: null,
  selectedRuntimeId: null,
  operationResult: "Runtime fixture operation result.",
  operationError: "",
  externalJdkPath: "C:\\Program Files\\Java\\jdk-21",
  externalJdkChecks: [],
  externalJdkResult: "External JDK fixture is ready for verification.",
  externalJdkError: "",
  page: 1,
};

export const fileAssociationsAcceptanceFixture: FileAssociationUiState = {
  report: {
    totalExtensions: 3,
    manageableExtensions: 3,
    missingAppCount: 0,
    records: [
      { extension: ".txt", currentAppName: "Notepad", risk: "low", source: "registry" },
      { extension: ".md", currentAppName: "VS Code", risk: "low", source: "registry" },
      { extension: ".json", currentAppName: "VS Code", risk: "low", source: "registry" },
    ],
  } as unknown as FileAssociationUiState["report"],
  backups: [{ backupName: "assoc-backup-fixture", createdAt: "2026-07-09T00:00:00Z", path: "C:\\Temp\\assoc-backup.json" }] as unknown as FileAssociationUiState["backups"],
  plan: {
    planId: "assoc-plan-fixture",
    targetAppName: "VS Code",
    targetExecutable: "C:\\Program Files\\Microsoft VS Code\\Code.exe",
    backupPath: "C:\\Temp\\assoc-backup.json",
    warnings: [],
    riskLevel: "high",
    requiresConfirmationToken: true,
    planFingerprint: "assoc-plan-fixture-fingerprint",
    changes: [],
  } as unknown as FileAssociationUiState["plan"],
  activeTab: "overview",
  filter: { keyword: ".txt", risk: "", category: "", onlyMissingApp: false },
  selectedExtensions: new Set([".txt"]),
  targetAppName: "VS Code",
  targetExecutable: "C:\\Program Files\\Microsoft VS Code\\Code.exe",
  appSearch: null,
  appSearchStatus: "idle",
  appSearchError: "",
  applyResult: null,
  rollbackResult: null,
  selectionResult: "Executable selected.",
  applyResultMessage: "Fixture apply result.",
  operationError: "",
};

export const acceptanceFixtures = {
  ports: portsAcceptanceFixture,
  cleanup: cleanupAcceptanceFixture,
  runtimes: runtimeAcceptanceFixture,
  fileAssociations: fileAssociationsAcceptanceFixture,
  toolchains: {
    ...toolchainWorkbenchInitialState,
    report: {
      git: {
        git: acceptanceTool("Git", "C:\\Program Files\\Git\\cmd\\git.exe"),
        gitBashPath: "C:\\Program Files\\Git\\bin\\bash.exe",
        userName: "Acceptance User",
        userEmail: "acceptance@example.invalid",
        ssh: acceptanceTool("OpenSSH", "C:\\Windows\\System32\\OpenSSH\\ssh.exe"),
        sshKeyExists: true,
        publicKeyPath: "C:\\Users\\Acceptance\\.ssh\\id_ed25519.pub",
        publicKey: "redacted fixture key",
        githubSshStatus: "Authenticated fixture",
        githubHttpsStatus: "Reachable fixture",
        gitLfs: acceptanceTool("Git LFS", "C:\\Program Files\\Git LFS\\git-lfs.exe"),
        globalConfigPath: "C:\\Users\\Acceptance\\.gitconfig",
      },
      node: {
        tools: [acceptanceTool("Node.js", "C:\\Program Files\\nodejs\\node.exe"), acceptanceTool("npm", "C:\\Program Files\\nodejs\\npm.cmd")],
        npmPrefix: "C:\\Users\\Acceptance\\AppData\\Roaming\\npm",
        npmRegistry: "https://registry.npmjs.org/",
        pnpmStorePath: "C:\\Users\\Acceptance\\AppData\\Local\\pnpm\\store",
        npmConfigPath: "C:\\Users\\Acceptance\\.npmrc",
      },
      python: {
        tools: [acceptanceTool("pip", "C:\\Python313\\python.exe"), acceptanceTool("uv", "C:\\Python313\\python.exe")],
        pipConfig: "global.index-url=https://pypi.org/simple",
        pipIndexUrl: "https://pypi.org/simple",
        pipConfigPath: "C:\\Users\\Acceptance\\AppData\\Roaming\\pip\\pip.ini",
      },
      generatedAt: "2026-07-12T00:00:00Z",
    },
    platform: {
      go: { go: acceptanceTool("Go", "C:\\Go\\bin\\go.exe"), goroot: "C:\\Go", gopath: "C:\\Users\\Acceptance\\go", goproxy: "https://proxy.golang.org,direct", gomodcache: "C:\\Users\\Acceptance\\go\\pkg\\mod" },
      rust: { tools: [acceptanceTool("rustup", "C:\\Users\\Acceptance\\.cargo\\bin\\rustup.exe"), acceptanceTool("rustc", "C:\\Users\\Acceptance\\.cargo\\bin\\rustc.exe")], defaultToolchain: "stable-x86_64-pc-windows-msvc", installedToolchains: ["stable-x86_64-pc-windows-msvc"], msvcBuildTools: "Visual Studio Build Tools fixture", cargoConfigPath: "C:\\Users\\Acceptance\\.cargo\\config.toml" },
      dotnet: { dotnet: acceptanceTool(".NET SDK", "C:\\Program Files\\dotnet\\dotnet.exe"), sdks: ["8.0.100"], runtimes: ["Microsoft.NETCore.App 8.0.0"], nugetConfigPath: "C:\\Users\\Acceptance\\.nuget\\NuGet\\NuGet.Config" },
      mirrors: { npmRegistry: "https://registry.npmjs.org/", pipIndexUrl: "https://pypi.org/simple", goProxy: "https://proxy.golang.org,direct", mavenSettingsPath: "C:\\Users\\Acceptance\\.m2\\settings.xml", mavenSettingsExists: true, gradleInitPath: "C:\\Users\\Acceptance\\.gradle\\init.gradle", gradleInitExists: true, cargoConfigPath: "C:\\Users\\Acceptance\\.cargo\\config.toml", cargoConfigExists: true },
      chsrc: acceptanceTool("chsrc", "C:\\Tools\\chsrc.exe"),
      chsrcRecovery: { missing: false, explanation: ["fixture"], scoopCommand: "scoop install chsrc", wingetCommand: "winget install RubyMetric.chsrc", officialUrl: "https://github.com/RubyMetric/chsrc", fallbackFeatures: ["npm", "pip"] },
      generatedAt: "2026-07-12T00:00:00Z",
    },
    system: {
      docker: { name: "Docker", installed: true, version: "27.0.0", path: "C:\\Program Files\\Docker\\Docker\\resources\\bin\\docker.exe", detail: "fixture" },
      dockerInfo: "Docker Engine 27.0.0",
      dockerDesktopPath: "C:\\Program Files\\Docker\\Docker\\Docker Desktop.exe",
      wsl: { name: "WSL", installed: true, version: "2.3.0", path: "C:\\Windows\\System32\\wsl.exe", detail: "fixture" },
      wslStatus: "Default Version: 2",
      wslDistributions: ["Ubuntu Running 2", "Debian Stopped 2"],
      wslItems: [
        { name: "Ubuntu", state: "Running", version: "2", isDefault: true },
        { name: "Debian", state: "Stopped", version: "2", isDefault: false },
      ],
    },
    services: [
      {
        id: "mysql",
        name: "MySQL",
        port: 3306,
        occupied: true,
        pid: 4100,
        processName: "mysqld.exe",
        processPath: "C:\\Program Files\\MySQL\\MySQL Server 8.4\\bin\\mysqld.exe",
        serviceNames: ["MySQL84"],
        safeToStop: true,
        connectionCommand: "mysql -h 127.0.0.1 -P 3306 -u root -p",
        installed: true,
        serviceName: "MySQL84",
        serviceState: "Running",
        binaryPath: "\"C:\\Program Files\\MySQL\\MySQL Server 8.4\\bin\\mysqld.exe\" --service",
        executablePath: "C:\\Program Files\\MySQL\\MySQL Server 8.4\\bin\\mysqld.exe",
        installDirectory: "C:\\Program Files\\MySQL\\MySQL Server 8.4\\bin",
        pathStatus: "Executable and installation directory verified by the backend.",
        logPath: "C:\\Windows\\System32\\winevt\\Logs\\Application.evtx",
        logPathReason: "Windows Application event log queried by the backend.",
      },
    ],
    selectedServiceId: "mysql",
    network: {
      checks: [{ name: "GitHub", url: "https://github.com", success: true, status: "200", elapsedMs: 42 }],
      proxy: [["HTTPS_PROXY", "not set"]],
    },
    cacheEntries: [{ name: "fixture.zip", path: "C:\\DevEnvManager\\downloads\\fixture.zip", size: 1024, sha256: "a".repeat(64) }],
    cacheInspected: true,
  } satisfies ToolchainWorkbenchState,
};
