import type { CommandArgs, InvokeClient } from "../core/invoke";
import { acceptanceFixtures } from "./fixtures";

export type MockInvokeMap = Record<string, unknown | ((args?: CommandArgs) => unknown | Promise<unknown>)>;

export function createMockInvokeClient(overrides: MockInvokeMap = {}): InvokeClient {
  const commands: MockInvokeMap = {
    scan_ports: acceptanceFixtures.ports.snapshot,
    enrich_port_scan: acceptanceFixtures.ports.snapshot,
    port_scan_status: acceptanceFixtures.ports.snapshot,
    cancel_port_scan: { success: true, message: "Fixture scan cancelled." },
    create_port_resolution_plan: acceptanceFixtures.ports.plan,
    execute_port_resolution_plan: acceptanceFixtures.ports.executionResult,
    scan_file_associations: acceptanceFixtures.fileAssociations.report,
    create_file_association_plan: acceptanceFixtures.fileAssociations.plan,
    scan_cleanup_targets: acceptanceFixtures.cleanup.scan,
    inspect_maintenance_overview: acceptanceFixtures.cleanup.overview,
    inspect_desktop: acceptanceFixtures.cleanup.desktop,
    create_desktop_archive_plan: {
      planId: "fixture-desktop-archive",
      createdAt: "1700000000",
      source: "C:\\Users\\Fixture\\Desktop",
      target: "D:\\DevEnvArchive\\DesktopArchive",
      mode: "desktop_archive",
      estimatedBytes: 2048,
      itemCount: 1,
      risk: "high",
      requiresAdmin: false,
      reversible: true,
      selectedItems: [],
      warnings: [],
    },
    execute_desktop_archive_plan: {
      planId: "fixture-desktop-archive",
      success: true,
      movedBytes: 2048,
      movedItems: 1,
      targetPath: "D:\\DevEnvArchive\\DesktopArchive",
      junctionCreated: false,
      failures: [],
      rollbackId: "fixture-desktop-rollback",
      receipts: [],
      reportMarkdown: "# Fixture Desktop Archive",
    },
    create_desktop_cleanup_plan: {
      planId: "fixture-desktop-recycle",
      createdAt: "1700000000",
      source: "C:\\Users\\Fixture\\Desktop",
      target: "Recycle Bin",
      mode: "desktop_recycle",
      estimatedBytes: 2048,
      itemCount: 1,
      risk: "medium",
      requiresAdmin: false,
      reversible: true,
      selectedItems: [],
      warnings: [],
    },
    execute_desktop_cleanup_plan: {
      planId: "fixture-desktop-recycle",
      success: true,
      movedBytes: 2048,
      movedItems: 1,
      targetPath: "Recycle Bin",
      junctionCreated: false,
      failures: [],
      receipts: [],
      reportMarkdown: "# Fixture Desktop Recycle",
    },
    open_recycle_bin: { success: true, message: "Fixture Recycle Bin opened." },
    inspect_recycle_bin: acceptanceFixtures.cleanup.recycleBin,
    create_recycle_bin_cleanup_plan: {
      planId: "fixture-recycle-bin-cleanup",
      createdAt: "1784213400",
      selectedDrives: ["D:"],
      itemIds: ["fixture-recycle-item"],
      itemCount: 1,
      estimatedBytes: 4096,
      snapshotFingerprint: "fixture-recycle-bin-fingerprint",
      riskLevel: "critical",
      warnings: ["permanent-removal", "scope-by-volume", "snapshot-must-match"],
    },
    execute_recycle_bin_cleanup_plan: {
      planId: "fixture-recycle-bin-cleanup",
      success: true,
      beforeItemCount: 1,
      beforeBytes: 4096,
      afterItemCount: 0,
      afterBytes: 0,
      cleanedItems: 1,
      cleanedBytes: 4096,
      selectedDrives: ["D:"],
      failures: [],
      message: "Fixture Recycle Bin cleanup verified.",
    },
    set_port_scan_preferences: { success: true, message: "Fixture port scan preferences saved." },
    discover_runtimes: acceptanceFixtures.runtimes.runtimes,
    inspect_system_platforms: acceptanceFixtures.toolchains.system,
    inspect_toolchains: acceptanceFixtures.toolchains.report,
    inspect_platform_toolchains: acceptanceFixtures.toolchains.platform,
    inspect_local_services: acceptanceFixtures.toolchains.services,
    open_docker_desktop: { success: true, message: "Docker Desktop fixture launched." },
    manage_system_platform: { success: true, message: "Platform fixture action completed." },
    open_local_service_directory: { success: true, message: "Service directory fixture opened." },
    local_service_logs: "Fixture Windows Application event log entry.",
    manage_local_service: { success: true, message: "Service fixture action completed." },
    run_toolchain_action: { success: true, message: "Toolchain fixture action completed." },
    run_platform_action: { success: true, message: "Platform toolchain fixture action completed." },
    run_chsrc_action: { success: true, message: "official" },
    network_diagnostics: acceptanceFixtures.toolchains.network,
    cache_entries: acceptanceFixtures.toolchains.cacheEntries,
    clear_download_cache: { success: true, message: "Managed cache fixture cleared." },
    ...overrides,
  };

  return {
    async invoke<T = unknown>(command: string, args?: CommandArgs): Promise<T> {
      if (!(command in commands)) {
        throw new Error(`Mock invoke command is not registered: ${command}`);
      }
      const value = commands[command];
      return (typeof value === "function" ? await value(args) : value) as T;
    },
  };
}
