export const acceptanceSelectors = {
  cleanup: {
    diskOverviewSection: "cleanup-disk-overview-entry",
    diskOverviewRefresh: "cleanup-disk-overview-action",
    diskOverviewResult: "cleanup-disk-overview-result",
    partitionExpansionSection: "cleanup-partition-expansion-section",
    partitionExpansionCreate: "cleanup-expansion-create-action",
    partitionExpansionExecute: "cleanup-expansion-execute-action",
    partitionExpansionPlan: "cleanup-expansion-plan-preview",
    partitionExpansionReceipt: "cleanup-expansion-backup-receipt",
    partitionExpansionResult: "cleanup-expansion-result",
    duplicateFilesSection: "cleanup-duplicate-large-files-entry",
    duplicateFilesScan: "cleanup-duplicate-large-files-action",
    duplicateFilesResult: "cleanup-duplicate-large-files-result",
    desktopArchiveSection: "cleanup-desktop-archive-section",
    desktopArchivePlan: "cleanup-desktop-archive-plan-action",
    desktopArchiveResult: "cleanup-desktop-archive-execute-result",
    downloadsArchiveSection: "cleanup-downloads-archive-section",
    downloadsArchivePlan: "cleanup-downloads-archive-plan-action",
    downloadsArchiveResult: "cleanup-downloads-archive-execute-result",
    inlineError: "cleanup-inline-error",
    operationResult: "cleanup-operation-result",
  },
  ports: {
    tableSection: "ports-table-section",
    row: "ports-row",
    rowCloseabilityReason: "ports-row-closeability-reason",
    createPlan: "ports-create-plan",
    executePlan: "ports-execute-plan",
    planPreview: "ports-plan-preview",
    executeResult: "ports-execute-result",
    inlineGuidance: "ports-inline-guidance",
  },
  runtime: {
    installJdkGroup: "runtime-install-jdk-group",
    installNodeGroup: "runtime-install-node-group",
    installPythonGroup: "runtime-install-python-group",
    installGoGroup: "runtime-install-go-group",
    installMavenGroup: "runtime-install-maven-group",
    installGradleGroup: "runtime-install-gradle-group",
    installedList: "runtime-installed-list",
    operationResult: "runtime-operation-result",
  },
  fileAssociations: {
    searchInput: "file-associations-search-input",
    recordsTable: "file-associations-records-table",
    createPlan: "file-associations-create-plan",
    planPreview: "file-associations-plan-preview",
    rollbackInfo: "file-associations-rollback-info",
  },
  toolchains: {
    ecosystems: "toolchains-ecosystems-result",
    actionPreview: "toolchains-action-preview",
    actionResult: "toolchains-action-result",
    mirrorPreview: "toolchains-mirror-preview",
    mirrorResult: "toolchains-mirror-result",
    networkResult: "toolchains-network-result",
    cacheResult: "toolchains-cache-result",
    cacheOperationResult: "toolchains-cache-operation-result",
    platformDocker: "platform-docker-section",
    platformPreview: "platform-operation-preview",
    platformResult: "platform-operation-result",
    serviceTable: "local-services-table",
    serviceDirectoryResult: "local-service-directory-result",
    serviceLogsResult: "local-service-logs-result",
    servicePreview: "local-service-operation-preview",
    serviceResult: "local-service-operation-result",
    mysqlControls: "toolchains-mysql-controls",
    mysqlCandidate: "toolchains-mysql-candidate-select",
    mysqlAction: "toolchains-mysql-action-select",
    mysqlBackupDestination: "toolchains-mysql-backup-destination",
    mysqlPlan: "toolchains-mysql-plan-preview",
    mysqlResult: "toolchains-mysql-result",
  },
  quality: {
    persistentError: "global-persistent-error",
    persistentResult: "global-persistent-result",
  },
} as const;

export type AcceptanceSelectors = typeof acceptanceSelectors;
